// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/core/v1/core.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreService_ExecuteCheck_FullMethodName    = "/uptimeping.core.v1.CoreService/ExecuteCheck"
	CoreService_GetCheckStatus_FullMethodName  = "/uptimeping.core.v1.CoreService/GetCheckStatus"
	CoreService_GetCheckHistory_FullMethodName = "/uptimeping.core.v1.CoreService/GetCheckHistory"
)

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoreService предоставляет методы для выполнения проверок
type CoreServiceClient interface {
	// ExecuteCheck выполняет проверку немедленно
	ExecuteCheck(ctx context.Context, in *ExecuteCheckRequest, opts ...grpc.CallOption) (*CheckResult, error)
	// GetCheckStatus возвращает текущий статус проверки
	GetCheckStatus(ctx context.Context, in *GetCheckStatusRequest, opts ...grpc.CallOption) (*CheckStatusResponse, error)
	// GetCheckHistory возвращает историю выполнения проверки
	GetCheckHistory(ctx context.Context, in *GetCheckHistoryRequest, opts ...grpc.CallOption) (*GetCheckHistoryResponse, error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) ExecuteCheck(ctx context.Context, in *ExecuteCheckRequest, opts ...grpc.CallOption) (*CheckResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResult)
	err := c.cc.Invoke(ctx, CoreService_ExecuteCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetCheckStatus(ctx context.Context, in *GetCheckStatusRequest, opts ...grpc.CallOption) (*CheckStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckStatusResponse)
	err := c.cc.Invoke(ctx, CoreService_GetCheckStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetCheckHistory(ctx context.Context, in *GetCheckHistoryRequest, opts ...grpc.CallOption) (*GetCheckHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckHistoryResponse)
	err := c.cc.Invoke(ctx, CoreService_GetCheckHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServiceServer is the server API for CoreService service.
// All implementations must embed UnimplementedCoreServiceServer
// for forward compatibility.
//
// CoreService предоставляет методы для выполнения проверок
type CoreServiceServer interface {
	// ExecuteCheck выполняет проверку немедленно
	ExecuteCheck(context.Context, *ExecuteCheckRequest) (*CheckResult, error)
	// GetCheckStatus возвращает текущий статус проверки
	GetCheckStatus(context.Context, *GetCheckStatusRequest) (*CheckStatusResponse, error)
	// GetCheckHistory возвращает историю выполнения проверки
	GetCheckHistory(context.Context, *GetCheckHistoryRequest) (*GetCheckHistoryResponse, error)
	mustEmbedUnimplementedCoreServiceServer()
}

// UnimplementedCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServiceServer struct{}

func (UnimplementedCoreServiceServer) ExecuteCheck(context.Context, *ExecuteCheckRequest) (*CheckResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCheck not implemented")
}
func (UnimplementedCoreServiceServer) GetCheckStatus(context.Context, *GetCheckStatusRequest) (*CheckStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCheckStatus not implemented")
}
func (UnimplementedCoreServiceServer) GetCheckHistory(context.Context, *GetCheckHistoryRequest) (*GetCheckHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCheckHistory not implemented")
}
func (UnimplementedCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {}
func (UnimplementedCoreServiceServer) testEmbeddedByValue()                     {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_ExecuteCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ExecuteCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ExecuteCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ExecuteCheck(ctx, req.(*ExecuteCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetCheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetCheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetCheckStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetCheckStatus(ctx, req.(*GetCheckStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetCheckHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetCheckHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetCheckHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetCheckHistory(ctx, req.(*GetCheckHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uptimeping.core.v1.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCheck",
			Handler:    _CoreService_ExecuteCheck_Handler,
		},
		{
			MethodName: "GetCheckStatus",
			Handler:    _CoreService_GetCheckStatus_Handler,
		},
		{
			MethodName: "GetCheckHistory",
			Handler:    _CoreService_GetCheckHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/core/v1/core.proto",
}
