// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/cli/v1/cli.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CLIService_ExecuteCommand_FullMethodName      = "/uptimeping.cli.v1.CLIService/ExecuteCommand"
	CLIService_GetCommandSchema_FullMethodName    = "/uptimeping.cli.v1.CLIService/GetCommandSchema"
	CLIService_StreamCommandOutput_FullMethodName = "/uptimeping.cli.v1.CLIService/StreamCommandOutput"
)

// CLIServiceClient is the client API for CLIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CLIService предоставляет методы для командной строки
type CLIServiceClient interface {
	// ExecuteCommand выполняет команду CLI
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
	// GetCommandSchema возвращает схему команд CLI
	GetCommandSchema(ctx context.Context, in *GetCommandSchemaRequest, opts ...grpc.CallOption) (*CommandSchema, error)
	// StreamCommandOutput потоково передает вывод команды
	StreamCommandOutput(ctx context.Context, in *StreamCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamCommandResponse], error)
}

type cLIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCLIServiceClient(cc grpc.ClientConnInterface) CLIServiceClient {
	return &cLIServiceClient{cc}
}

func (c *cLIServiceClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteCommandResponse)
	err := c.cc.Invoke(ctx, CLIService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIServiceClient) GetCommandSchema(ctx context.Context, in *GetCommandSchemaRequest, opts ...grpc.CallOption) (*CommandSchema, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandSchema)
	err := c.cc.Invoke(ctx, CLIService_GetCommandSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIServiceClient) StreamCommandOutput(ctx context.Context, in *StreamCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamCommandResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CLIService_ServiceDesc.Streams[0], CLIService_StreamCommandOutput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamCommandRequest, StreamCommandResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CLIService_StreamCommandOutputClient = grpc.ServerStreamingClient[StreamCommandResponse]

// CLIServiceServer is the server API for CLIService service.
// All implementations must embed UnimplementedCLIServiceServer
// for forward compatibility.
//
// CLIService предоставляет методы для командной строки
type CLIServiceServer interface {
	// ExecuteCommand выполняет команду CLI
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	// GetCommandSchema возвращает схему команд CLI
	GetCommandSchema(context.Context, *GetCommandSchemaRequest) (*CommandSchema, error)
	// StreamCommandOutput потоково передает вывод команды
	StreamCommandOutput(*StreamCommandRequest, grpc.ServerStreamingServer[StreamCommandResponse]) error
	mustEmbedUnimplementedCLIServiceServer()
}

// UnimplementedCLIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCLIServiceServer struct{}

func (UnimplementedCLIServiceServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedCLIServiceServer) GetCommandSchema(context.Context, *GetCommandSchemaRequest) (*CommandSchema, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommandSchema not implemented")
}
func (UnimplementedCLIServiceServer) StreamCommandOutput(*StreamCommandRequest, grpc.ServerStreamingServer[StreamCommandResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamCommandOutput not implemented")
}
func (UnimplementedCLIServiceServer) mustEmbedUnimplementedCLIServiceServer() {}
func (UnimplementedCLIServiceServer) testEmbeddedByValue()                    {}

// UnsafeCLIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CLIServiceServer will
// result in compilation errors.
type UnsafeCLIServiceServer interface {
	mustEmbedUnimplementedCLIServiceServer()
}

func RegisterCLIServiceServer(s grpc.ServiceRegistrar, srv CLIServiceServer) {
	// If the following call pancis, it indicates UnimplementedCLIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CLIService_ServiceDesc, srv)
}

func _CLIService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLIService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServiceServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLIService_GetCommandSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommandSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIServiceServer).GetCommandSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLIService_GetCommandSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIServiceServer).GetCommandSchema(ctx, req.(*GetCommandSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLIService_StreamCommandOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CLIServiceServer).StreamCommandOutput(m, &grpc.GenericServerStream[StreamCommandRequest, StreamCommandResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CLIService_StreamCommandOutputServer = grpc.ServerStreamingServer[StreamCommandResponse]

// CLIService_ServiceDesc is the grpc.ServiceDesc for CLIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CLIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uptimeping.cli.v1.CLIService",
	HandlerType: (*CLIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _CLIService_ExecuteCommand_Handler,
		},
		{
			MethodName: "GetCommandSchema",
			Handler:    _CLIService_GetCommandSchema_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCommandOutput",
			Handler:       _CLIService_StreamCommandOutput_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/cli/v1/cli.proto",
}
